enhancement: replacing primereact dialogues with ARC - part 1
ynput/ayon-frontend pull request #357
Opened 2024-04-18 15:07 UTC by LudoHolbik

## Changelog Description
- replacing primereact dialogues with ARC dialogues

2024-05-03 09:52 UTC, LudoHolbik commented
Current state of last two problematic parts - Add folder (NewSequence) sequence and Add Tasks (NewEntity)

https://github.com/ynput/ayon-frontend/assets/16327908/e3bbf75f-f58e-4adc-bea9-f95a16dd28e5

2024-05-05 12:19 UTC, Innders requested changes

2024-05-05 12:19 UTC, Innders commented on src/pages/ProjectManagerPage/NewProjectDialog/NewProject.jsx
Modal impossible to open because it closes straight away?

2024-05-05 12:19 UTC, Innders commented on src/pages/ServicesPage/NewServiceDialog.jsx
Dropdowns hidden behind the modal.

2024-05-05 12:19 UTC, Innders commented on src/pages/ServicesPage/NewServiceDialog.jsx
Height: fit-content, we should be able to see the whole form without a scroll.

<img width="1425" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/f671b649-4a48-45e7-a11e-a915354ec857">

2024-05-05 12:19 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/RenameUserDialog.jsx
Footer wrong

<img width="611" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/a65220ae-6349-4c39-b3e1-55d6f80cc7df">

2024-05-05 12:19 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/SetPasswordDialog.jsx
Footer wrong

<img width="454" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/998fdbb2-7678-4b51-b891-e536d20eeac7">

2024-05-05 12:19 UTC, Innders commented on src/pages/TeamsPage/TeamsPage.jsx
Footer issues

<img width="484" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/e4ae5ccb-02d3-4512-8884-64ebee38a81a">

2024-05-06 08:51 UTC, LudoHolbik commented on src/pages/SettingsPage/UsersSettings/SetPasswordDialog.jsx
Fixed by recent ARC release:

<img width="734" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/0ad57411-00d1-4da6-9278-afdd8b31e712">

2024-05-06 08:53 UTC, LudoHolbik commented on src/pages/SettingsPage/UsersSettings/RenameUserDialog.jsx
Fixed by ARC release:
<img width="1076" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/9294f510-4dc9-498c-b5b0-0845f9ebc70e">

2024-05-06 09:00 UTC, LudoHolbik commented on src/pages/TeamsPage/TeamsPage.jsx
Fixed by recent ARC release:
<img width="857" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/5559b020-6b5b-4826-b692-e52b745f92c1">

2024-05-06 19:10 UTC, Innders commented on src/pages/EditorPage/NewSequence.jsx
esc fixed, just need to center now

2024-05-06 19:12 UTC, Innders commented on src/containers/CopySettings/CopySettingsDialog.jsx
seems fixed

2024-05-06 19:14 UTC, Innders commented on src/containers/attributes/attributeEditor.jsx
dropdown seems fixed. This input is cut off. 
<img width="656" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/1d97edf4-f6e5-4810-b708-12f771f95dd2">

2024-05-08 09:13 UTC, LudoHolbik commented
Ready for review.

2024-05-08 11:47 UTC, Innders approved these changes
Approved 🥳

2024-05-08 11:47 UTC, merged