fix(serviceUser): Custom form on adding service user, removing servic…
ynput/ayon-frontend pull request #636
Opened 2024-07-19 00:03 UTC by flynput

Existing non service users cannot be converted to Service Users and vice versa. The following actions were taken to avoid that:
- Custom form for service user creation, only username, active/inactive & generated key form fields are required
- Non service users cannot be converted to Service users, option removed from form

2024-07-19 06:00 UTC, Innders requested changes
Getting there but we just need a few UI changes.

### For a service user remove all the unnecessary fields.

![image](https://github.com/user-attachments/assets/a970577d-f006-44ae-bed3-9a41461f1f9d)

It should look something like this:
![image](https://github.com/user-attachments/assets/b5b7fec9-6032-495e-998d-b549a4a364cc)

- label width `160px`
- API key padding `var(--padding-l)`
- API key background color `var(--md-sys-color-surface-container-high)`

### For a normal user remove the service key fields

![image](https://github.com/user-attachments/assets/f713d123-62e0-4814-8b27-06282c885b1e)

### Suggestion

Write two completely separate forms for **normal user** and **service user** whilst sharing some logic like submitting.

Thanks!

2024-07-19 06:02 UTC, Innders commented
Also small note, I just pushed a commit to switch the buttons around :)

2024-07-19 07:21 UTC, BigRoy commented
> Getting there but we just need a few UI changes.
> ### For a service user remove all the unnecessary fields.
> 
> ![image](https://private-user-images.githubusercontent.com/49156310/350254110-a970577d-f006-44ae-bed3-9a41461f1f9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzM4ODQsIm5iZiI6MTcyMTM3MzU4NCwicGF0aCI6Ii80OTE1NjMxMC8zNTAyNTQxMTAtYTk3MDU3N2QtZjAwNi00NGFlLWJlZDMtOWE0MTQ2MWYxZjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3MTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDE0NjhlMjZiYTQyMTJiNDcwNmYyNGMzZjA1OWUxZTBiMWU1YWYwM2RiZGM2ZmJiMGJlMzZiYWU4YzBkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0lhcCOU9c5B8jvoJM1_C-40PmkqcywaCbNNbU2MQJTo)
> 
> It should look something like this: ![image](https://private-user-images.githubusercontent.com/49156310/350255640-b5b7fec9-6032-495e-998d-b549a4a364cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzM4ODQsIm5iZiI6MTcyMTM3MzU4NCwicGF0aCI6Ii80OTE1NjMxMC8zNTAyNTU2NDAtYjViN2ZlYzktNjAzMi00OTVlLTk5OGQtYjU0OWE0YTM2NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3MTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzNiYjM2MDM5YWI3Y2UxZjYzNjZhODljYzAxZTYxODg4MmFhNjIzYzUwY2UxOTBiOWQyOTk0Yjg3NTM2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VscndlhKblXMYq2wNiM5R61XniA82TmaNggUexPQ5gc)
> 
>     * label width `160px`
> 
>     * API key padding `var(--padding-l)`
> 
>     * API key background color `var(--md-sys-color-surface-container-high)`
> 
> 
> ### For a normal user remove the service key fields
> 
> ![image](https://private-user-images.githubusercontent.com/49156310/350256476-f713d123-62e0-4814-8b27-06282c885b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzM4ODQsIm5iZiI6MTcyMTM3MzU4NCwicGF0aCI6Ii80OTE1NjMxMC8zNTAyNTY0NzYtZjcxM2QxMjMtNjJlMC00ODE0LThiMjctMDYyODJjODg1YjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3MTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTE2N2QzMzFkMDkzNTc0MDA0MWZmM2EyYTRkYjM4NWMxZTlmNzY3ZmNkYmRiNTIxYjgyNjUwNjQyMjg2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zw24Q0J7srwalvL6NLoLMRmXk_EZj1NBYs_IM_sP6jo)
> ### Suggestion
> 
> Write two completely separate forms for **normal user** and **service user** whilst sharing some logic like submitting.
> 
> Thanks!

Question. Under the separator/divider should that **Access Control** label be like the header of that area - similar in size to the "Create new user" header? It feels a bit uesless at the same size with no attribute/control next to it. Or we just remove the label?

2024-07-19 10:45 UTC, Innders commented
> > ![image](https://private-user-images.githubusercontent.com/49156310/350256476-f713d123-62e0-4814-8b27-06282c885b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzM4ODQsIm5iZiI6MTcyMTM3MzU4NCwicGF0aCI6Ii80OTE1NjMxMC8zNTAyNTY0NzYtZjcxM2QxMjMtNjJlMC00ODE0LThiMjctMDYyODJjODg1YjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3MTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTE2N2QzMzFkMDkzNTc0MDA0MWZmM2EyYTRkYjM4NWMxZTlmNzY3ZmNkYmRiNTIxYjgyNjUwNjQyMjg2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zw24Q0J7srwalvL6NLoLMRmXk_EZj1NBYs_IM_sP6jo)
> 
> Question. Under the separator/divider should that **Access Control** label be like the header of that area - similar in size to the "Create new user" header? It feels a bit uesless at the same size with no attribute/control next to it. Or we just remove the label?

Agreed, I vote just remove

2024-07-22 10:19 UTC, martastain requested changes
When a service user is created, its API key does not work. When regenerated from the user editor, it works correctly. I can see you are handling "password" somehow, but API keys are stored differently: 

- create user without any password
- call `/api/users/{username}/password` with "apiKey" field set

that should ensure "apiKeyPreview" will be available in the user entity.

2024-07-22 20:04 UTC, Innders requested changes
Ensure PascalCase is used file names and component names.

2024-07-22 20:04 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
> +      password: password ? password : undefined,
I think most of these fields can be removed now as they don't apply to service users?

Password needs to be apiKey instead.

<img width="367" alt="image" src="https://github.com/user-attachments/assets/2757ecaf-405e-4bcf-b528-c960f296c66e">

2024-07-23 08:26 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
> +      await addUser({ name: formData.Username, user: preparePayload(formData, attributes, password) }).unwrap()
This needs to use `apiKey` instead of `password` as per docs: https://ayon.dev/docs#tag/Users/operation/create_user

2024-07-23 10:13 UTC, prodigel commented on src/containers/Feed/hooks/useUserMutations.js
> +  const [formData, setFormData] = useState(initialFormDataCallback)
That's how it was in the newUser component, no idea why, removing it

2024-07-23 11:28 UTC, Innders requested changes
Almost everything works 🥳 

Just one thing left now thanks

2024-07-23 11:28 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
> +      isOpen
I was trying to work out why cmd+enter wasn't working and realised that it's checking for a password. There is no password.
```suggestion
          validationPassed: formData.Username,
```

2024-07-23 11:28 UTC, Innders commented on src/pages/SettingsPage/UsersSettings/newServiceUser.jsx
> +          {...{ password, setPassword }}
I guess this and any other reference to password can be removed?
```suggestion
```

2024-07-23 12:47 UTC, merged