665 feed cannot identify status changes for multiple selected folderstasksversions
ynput/ayon-frontend pull request #700
Opened 2024-08-02 12:55 UTC by flynput

Showing detailed version info in status change activities depending on selection context
* displaying folder/task name on activity status change items when focused 
* product name included on version selection
* folder name included if multiple selected
* reverted change  that introduced bug which removed activity status icons

https://github.com/user-attachments/assets/f55c1513-42c1-4224-9cfe-3467d2942e60

closed #665

2024-08-02 13:55 UTC, BigRoy commented
Even though it's better (You can see what it's about) I wonder whether it's clean enough.

1. It feels somewhat disconnected from the status change text above it. It feels like a new line instead of like a subtitle or connected header/label.
2. I wonder if we need some consistency to still use ` / ` as separator like in other areas or whether ` | ` is better in this case and whether we can somehow get it clear what it's linked to (point 1) and then avoid the `( )` brackets surrounding it to avoid clutter.

Other than that, it's somewhat of an improvement so we could save the cosmetics for later if that's preferred.

2024-08-02 13:59 UTC, Innders requested changes
Looks good. We may tweak it in the future based on user feedback :)

Just one error to cleanup

2024-08-02 13:59 UTC, Innders commented on src/components/Feed/ActivityStatusChange/hooks/getContextParents.js
> +    tag.push(activity.activityData.parents.find((p) => p.type == 'folder')?.name)
I managed to create a type error by selecting multiple folders and then selecting a task.

![image](https://github.com/user-attachments/assets/3a735e76-a37c-4349-b4f2-101c9ccc8e82)
![image](https://github.com/user-attachments/assets/ebd4a866-e647-4ddb-a52e-6e9e8eb355eb)

2024-08-05 06:43 UTC, Innders commented
> 1. feels somewhat disconnected

I get your feeling. I've played around with it, what do you think of this @flynput @BigRoy ?

1. Removed `status changed` -  do we really need this text, is not obvious enough?
2. Moved entity name to after the user and replaced `|` with `/` as it's more a path.

I think this reads better. **User that did it** - **on something** - **and that change**

New format
![image](https://github.com/user-attachments/assets/0599f4f3-1485-4f5b-8d19-182c03d9c4a0)

Old format
![image](https://github.com/user-attachments/assets/7ba14f8a-cb4b-4c81-9c46-c6de8fa1d9b2)

2024-08-05 07:20 UTC, Innders approved these changes
💯

2024-08-05 09:34 UTC, merged