fix(users) Showing 'none' access users at the bottom of the table whe…
ynput/ayon-frontend pull request #727
Opened 2024-08-14 11:58 UTC by flynput

Users with no Project access are filtered out and appended to the sorted list when sorting by Project access, no matter the order.

https://github.com/user-attachments/assets/a236ce7a-05f2-4deb-90b0-6ebb5cf22e52

Closes #718

2024-08-14 14:44 UTC, Innders requested changes
Users with no access have gone to the bottom, nice!

Two things to do now:

- [ ] Inactive users have no access to even logging in so they should be last. (sorry I missed this)
- [ ] Better sorting of users with access described below.

The order should go (from top to bottom):

1. admin
2. manager
3. user with access (users with most access groups first)
4. service
5. users with access

![image](https://github.com/user-attachments/assets/a7cc5d42-4c6d-410d-a5bc-2921fe1342b8)

2024-08-14 22:41 UTC, flynput commented
Updated sorting strategy as requested.

https://github.com/user-attachments/assets/e585fa58-ff85-4703-8ebb-753984c8be2a

2024-08-15 06:15 UTC, Innders approved these changes
Awesome!

Users with access don't quite sort by number of access groups but it's none essential for this.

![image](https://github.com/user-attachments/assets/72bc9933-6479-4981-a754-1e9d0dbacc66)

And last thing to consider... this has become a pretty big function, is it worth breaking it out into its own file. Maybe in a helpers file or something? That would also allow for it to be written in TS maybe.

2024-08-16 05:52 UTC, Innders approved these changes

2024-08-16 06:43 UTC, merged