Editor: Listing & form improvements
ynput/ayon-frontend pull request #757
Opened 2024-08-28 08:16 UTC by flynput

"None" placeholder in editor listing when no tools are selected.
Refactoring formatAttributes and converted to TS.
Removed clear all from single-select enum fields in Editor details panel.

2024-09-02 14:35 UTC, Innders requested changes
Tools only has an option to clear to empty list now when it needs to be able to clear to null so it can be inherited.

_PR_
![image](https://github.com/user-attachments/assets/04506f59-5693-4546-a89b-6c96fad48d70)
_current (except that tooltip is wrong because that's clear to inherit not empty list)_
![image](https://github.com/user-attachments/assets/1939f781-6d81-4c7b-8f41-ec82ba34f579)


It works when I choose "a (inherited)" value but then I don't see the inherited value.

https://github.com/user-attachments/assets/0818939d-e58f-468f-990a-dbfd168f5d65

2024-09-05 14:14 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +                    return `inhreited - (${labels.join(', ')})`
type

2024-09-05 14:30 UTC, Innders requested changes
Getting there but still have some major bugs to clean up.

2024-09-05 14:30 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +                    return `inhreited - (${labels.join(', ')})`
typo `inherited`

2024-09-05 14:30 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
When selecting "inherited" value the dropdown should close straight away. It does not make sense to continue selecting more options.

![image](https://github.com/user-attachments/assets/cd5957b1-c1e6-4c8a-a68d-cd3f4f1fcee9)

And trying to save this selection causes an error.

![image](https://github.com/user-attachments/assets/d779dc3c-ff72-4d64-975d-3d19c08ad960)

2024-09-05 14:30 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
If I set inherited and then set a different value then the inherited value will still show.

https://github.com/user-attachments/assets/876c159d-4457-47ce-8b10-acea6c054844

2024-09-05 14:30 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
>                      <Dropdown
Overflow styling issue. Maybe it's an issue ARC?

![image](https://github.com/user-attachments/assets/71ce7efa-be96-4e00-8af6-5070a7251c41)

2024-09-05 14:30 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +                          ? 'var(--md-ref-palette-neutral-variant60'
use `--md-sys-color-outline` instead

2024-09-12 10:09 UTC, closed without merging

2024-09-12 10:10 UTC, flynput commented
Code rewritten, PR open on new branch, closing this one.