751 editorbrowser thumbnail
ynput/ayon-frontend pull request #775
Opened 2024-09-04 08:14 UTC by flynput

## Description of changes 

## Technical details

## Additional context

2024-09-04 18:02 UTC, flynput commented
@Innders WIP: Refactoring to unify context menu & upload handlers into one provider which stays on top of the StackedThumbnail component

2024-09-05 06:16 UTC, Innders commented on src/components/EntityThumbnailUploader/ThumbnailUploaderProvider.tsx
> +      label: 'Upload New Thumbnail',
Only capilized first letter


```suggestion
      label: 'Upload new thumbnail',
```

2024-09-05 06:49 UTC, Innders requested changes
Almost there, just a small things to go and then it will be perfect.

2024-09-05 06:49 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +          <EntityThumbnailUploader
The dropzone should span the full height of the right side panel.

![image](https://github.com/user-attachments/assets/534a51e4-cb06-4203-adf1-1db23e2acb44)

2024-09-05 06:49 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +                  <Button
These icons are now really big?

![image](https://github.com/user-attachments/assets/4b24c379-1e49-47bb-9a40-3dcc73544c53)

2024-09-05 06:49 UTC, Innders commented on src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx
> +        const promise = axios.post(
It seems the uploading logic is in this file and in [ThumbnailUploader](https://github.com/ynput/ayon-frontend/blob/d8c86bb66d5bbad8eec451cd5d15c3ff5f89f7bc/src/components/ThumbnailUploader/ThumbnailUploader.tsx#L50)?

Any reason why it's duplicated, could be a custom hook be used to that it is written once and reused twice?

2024-09-05 06:49 UTC, Innders commented on src/pages/EditorPage/EditorPanel.jsx
> +              const firstOperation = operations[0]
Only one thumbnail gets updates, which makes sense in this code. Use a forEach loop to update all.

![image](https://github.com/user-attachments/assets/909ecfe8-425c-48fb-98db-1866066326b5)

2024-09-05 06:49 UTC, Innders commented on src/components/EntityThumbnailUploader/EntityThumbnailUploader.tsx
> +        <input type="file" onChange={handleFileUpload} ref={inputRef} />
When uploading using the input, we should still see the uploading progress like in drag and drop. 


https://github.com/user-attachments/assets/286474b7-79e8-4178-a6bb-0f856a5f7bcb

2024-09-05 06:55 UTC, Innders commented on src/components/EntityThumbnailUploader/ThumbnailUploaderProvider.tsx
> +      label: 'Upload New Thumbnail',
And also use the `add_photo_alternative` icon to match the dropzone icon.

2024-09-05 10:03 UTC, flynput commented
https://github.com/user-attachments/assets/fd3518d0-bb17-438f-8c01-01da966cdc12

2024-09-05 11:16 UTC, Innders requested changes
Works really nice, great job 👍 

There is just one tiny thing I noticed. On the editor page you have to drag the file over the header (red box) to trigger to dropzone. The trigger should be the full height (green box). So you can drop files by dragging anywhere over the right side panel.

![image](https://github.com/user-attachments/assets/93b0b85e-7737-4ea9-97f6-bd6972c3f544)

https://github.com/user-attachments/assets/bd691975-4e4a-4bc1-96a7-653b7db3e04b

2024-09-05 14:18 UTC, flynput commented
> Works really nice, great job 👍
> 
> There is just one tiny thing I noticed. On the editor page you have to drag the file over the header (red box) to trigger to dropzone. The trigger should be the full height (green box). So you can drop files by dragging anywhere over the right side panel.
> 
> ![image](https://private-user-images.githubusercontent.com/49156310/364753546-93b0b85e-7737-4ea9-97f6-bd6972c3f544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDYxNjMsIm5iZiI6MTcyNTU0NTg2MywicGF0aCI6Ii80OTE1NjMxMC8zNjQ3NTM1NDYtOTNiMGI4NWUtNzczNy00ZWE5LTk3ZjYtYmQ2OTcyYzNmNTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE0MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzgyZDI3MjgxOWIyZjliNTQ5YTI5MmFkNDExNDYxNDY3ZDA3MzQ5YTRlMjk3ZTI4MWRjY2E5ZDI4NjNmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zokk18OTDHeS26PzY--9_yiXLLSTEIRXctNigrcb3rk)
> 
>  Screen.Recording.2024-09-05.at.12.17.24.mov

Updated!

2024-09-05 15:56 UTC, Innders approved these changes
Works. Approved!

2024-09-06 05:40 UTC, merged