Bundles: Cancelling file upload on window close
ynput/ayon-frontend pull request #808
Opened 2024-09-18 06:20 UTC by flynput

When uploading installers/addons, whenever the upload dialog is closed, an abort signal is sent to axios, stopping the upload.

https://github.com/user-attachments/assets/5c3eb6d1-7d71-4c4a-8f0a-1125216da61d

closes #733

2024-09-18 06:35 UTC, martastain commented
I think it should primarily prevent accidental closing of the dialog during the upload rather than aborting the process. It is really easy to click outside and lose the progress.

2024-09-18 10:23 UTC, Innders requested changes
Cool, could we also get a toast to let the user know the upload was cancelled? 

And also what Martin said:

- Prevent closing on escape and clicking outside when an upload it happening (a.k.a only the Close button works).
- Rename `Close` to `Cancel`

2024-09-20 07:52 UTC, mkolar commented
Looking good to me.

2024-09-20 12:46 UTC, Innders approved these changes

2024-09-20 12:46 UTC, merged