870 settings search all settings
ynput/ayon-frontend pull request #909
Opened 2024-10-29 15:44 UTC by flynput

Draft PR, ignore the code for now, I'll have to do 'a bit' of refactoring there.
Filtering settings can be tested, working now on a few missing pieces:
 - deep nested references are not mapped properly in the search object
 - multiple addons search - currently in the works
 - values search - at the moment only labels are matched.

Let me know what you think.

https://github.com/user-attachments/assets/776fce71-84ca-4184-b52e-1f43b9fcb0da

2024-10-31 07:40 UTC, flynput commented
Settings filtering can now be done on any number of selected addons, it uses - most - of the settings label and a string values. Screen recording was also updated. 

Let me know what you think.

2024-10-31 09:35 UTC, Innders requested changes
- [ ] Number values aren't matched.
- [ ] Clearing the search field doesn't always clear the filtering
https://github.com/user-attachments/assets/b58152b9-a1f8-489a-bfae-058506543c8f


- [ ] Labels don't match
https://github.com/user-attachments/assets/c267b91e-c221-4834-a44c-b8fad39ed3c7

- [ ] Sometimes the groups don't close.
- [ ] Should the groups expand when opening?

https://github.com/user-attachments/assets/6396f336-ff59-4b71-8dd7-ea1630ea4ba4

- [ ] Expanding and collapsing affects all these groups?
https://github.com/user-attachments/assets/ff8ec12e-f7ea-434b-be21-661bd967e166

- [ ] Value not match here
https://github.com/user-attachments/assets/4bb30cc4-02c1-4e5e-806e-5fd3977b5417

2024-10-31 09:35 UTC, Innders commented on src/containers/AddonSettings/SettingsListHeader.tsx
> +        placeholder="Search & filter settings"
Search and filter settings

2024-10-31 14:26 UTC, flynput commented
Fixed the following issues:
- Labels and values for numbers (int & numeric schema types) should match now, same goes for list items labels/values
- Clearing filter text should reset form to full nodes tree

2024-10-31 15:46 UTC, Innders approved these changes
Approved, lets get it deploy to experimental for some more testing!

2024-10-31 16:59 UTC, BigRoy commented
Tested Experimental `1.5.4+202410311657` + Windows + Firefox

---


![image](https://github.com/user-attachments/assets/81a7091f-dcd5-40e0-b0b9-fded766e13ce)

1. Super-wide multiselection enum styling is off: `ayon+settings://applications/project_applications/profiles/0/applications`

Issue seems even worse in project settings? `ayon+settings://applications/project_applications/profiles?project=ayontest`

![image](https://github.com/user-attachments/assets/a88a2a73-06df-4f30-9870-acec3a9c4066)

2. Also, not sure if it should but searching for "Blender" does not find that value in there. Should it search for values?

Searching for "python" also doesn't find e.g. the Blender app definition arguments which has `--python-use-system-env` as value.

---

3. Is it correct that these list sections aren't full width anymore?

![image](https://github.com/user-attachments/assets/ce137033-a4d0-4d74-aa61-1cc9819c6c41)
![image](https://github.com/user-attachments/assets/6ce6e4ae-24c2-492e-9a1b-6e5d2acbd651)

---

Nice, search even works selecting multiple addons:

![image](https://github.com/user-attachments/assets/6dc0ffc3-4292-4f19-b7ec-ddded52c8d7e)

However in this case trying to expand one of the addon sections for me seems to expand all four of them? Bug?

2024-10-31 17:06 UTC, Innders commented
> However in this case trying to expand one of the addon sections for me seems to expand all four of them? Bug?

Separate bug not relevant to this PR.

2024-10-31 17:15 UTC, m-u-r-p-h-y commented
Searching for tag webreview used in settings is not returning correct result

webreview tag is used:
![image](https://github.com/user-attachments/assets/3ec9f20f-8e78-4e1c-bb03-a3d0d122fed5)

but not found
![image](https://github.com/user-attachments/assets/9d5a2534-36b3-4f63-8cf4-b039b607e0f9)

2024-10-31 17:20 UTC, m-u-r-p-h-y commented
`maya` is not found in application addon in profiles

<img width="411" alt="image" src="https://github.com/user-attachments/assets/bc52370b-52dd-4ab8-8f58-c82cefd5cd2a">

2024-11-01 10:22 UTC, BigRoy commented
Nice! Much better now.

This is what stands out:

### Filter inside lists?

I wonder if with this search query it should filter out the other tools?

![image](https://github.com/user-attachments/assets/8048c9ae-aed6-46a4-88bd-b5dcb02905f8)

---

### Cosmetics: Should we highlight the search bar if active?

Also, I wonder if the search bar need some highlighting or whatever if there's an active search filter because leaving e.g. a space in there will be VERY confusing. But also just having a decent text filter set but then going to other addons it can be easily missed that the search filter is still active.

---

### Cosmetics: Search bar rounded corners?

On firefox it looks like the search bar styling lacks rounded corners like other text fields.

**Firefox:**

![image](https://github.com/user-attachments/assets/ad76af06-efda-4396-8923-4dd56b8d1dad)

**Chrome:**

![image](https://github.com/user-attachments/assets/82b7e421-7530-48ce-9c8f-842947d1a0f4)

2024-11-01 10:26 UTC, m-u-r-p-h-y commented
I'm not sure if this is relevant to this PR, but it would be great to have a `clear` button so we do not have to click the search bar and manually remove the search string to restore it to its default state. (quite annoying)

2024-11-01 10:30 UTC, martastain approved these changes

2024-11-01 10:30 UTC, merged